$ANSIBLE_VAULT;1.1;AES256
36303132366230313239326636666532636237366165393938653235343266313533363331656564
3135356364653038323761373230363061306138626330340a313232383763386362323433666662
35616563343236636635313361303638656661343739366462363035323063613835373566333066
3636336334346637610a313538626237623932346664363666656233646464343563646530376365
34343532366534643962393838353534626462316438333631623730653439646139373063626637
61646137396266623964646262353735366362326364373761653933363435303264353631346639
61633734643662376362396463623463336163363934323134613632393830396261323337366264
66336337313334356433343731323231646236316563393163626437656437373262653439636366
33383465653833336239666666396364373861306562653534666338613737363535643338656238
64666364623830653430643666666530346638656462626239663332366531383765303535356530
32383639663661633838616662653134356335353031633038313938613030383362663031343161
61383664363161643935393632326631616362336630333936383261316435616134663739633932
30626335326235343134643366346164376633646239626233353366306165336430626333376333
63353564656638626135376234353933636433346164393730336565363866643366646663353365
38333532656131666164313334613666373130643536653064373135666665376637393363386130
37383933356234366439363863396561656332346561633965313665643930313932396364386137
61363762623463316134376239356265303436386538346631326639356532333664663234663161
39363236656234656437386339376466666434653837396237366332343063313333393564336636
63643232356662396536633264653364623261313664333432376666666465613233376537626435
30336237666137373234373330383964336462643130396162326330656164333336326431376561
38363061643966313536366631393231663561616131613934306633643963336435306438626430
64383262663931656639383632356666623665366365336334356166653038376566623062623164
34376464353334633538613531346332383965396635623930346630353262316361353733623733
31353537383563363834336332326439623434663439313866613731623662306165363263396132
34343566393538356463643133393666643836626134636266303739353730376131346664393734
63626639623938663033376634633132306164626366626232653963646262616562376537303936
613435646665333034383136393835323735
