$ANSIBLE_VAULT;1.1;AES256
37393661653239386538646462356632626536643736386365313730306661333165396463336434
3734366139333366303931333039393866383437316632640a643461333637326566623333653337
38363437333631626230343261623962663736663932633264646666316239643734323863663535
3766646265383137380a303136303138333134336162633261316533316237353735363430613638
32663532333565323533326630633265303930643265393830653033313265366364326263393730
36353935356531393032313065633464353765633336663161663630663633663832303931316334
30616230383132313066383465306230396336313739343333636365383338393232613435386261
31636262653231303231336565376335396230383463373735303737316337306666653334323135
35306466353732326139613333663963346133373633346338376133343138306263626431306431
30396139353638623235343132653366623033326232663030633837303732636563316537396133
37373063316230343438356539383963356235636661313736366137303439353766656238326263
32326535306362343831343364633235643764366434356565323736393838356662633534653663
64323033383734353136383366643361333231326439366133336532386638396139663164313734
38643163386333356665303563663664653634353463373438613863323734366531303238303238
37616364396664333466623766363437336338323465353935366561396262626138633664626634
63666161353266663766303131333334656430386663313262323864623835633033306534343865
61306239363333373232303335373538333763363236663334663238326533636237393565396536
30666265633433386633626639333535363862363238363636663638623136313863313034613865
63646236356333306462313664626333646337333032636162303230376232373430346161363732
63383434346432313136366465363539303831333939326437663865326165646133326665623566
39376262383766333862356266326437323863643665373530366562616664656432376563346632
30366531373134646363333332363566663537383462396366306434313932386135353933393436
35656562383365306330643130363962326338326265303935666164613464383864303335633331
64313230663230356336373963663864323866363436333131643638313734383238303338396336
36613133666537326433666161333966626435643562633437386166666464643730383331353332
35323332336532376265356366346138616638333965666531623135636535313137336630393361
65623737333966636262353432363630343964326532656537646433633262333634356138633263
64386464663364373637626466316361386430306134363631643831366236363065393265633961
3239
