$ANSIBLE_VAULT;1.1;AES256
35323530313130363732626236326435343061316239336238613135346639623234313366313965
3264633863343937373766396165346130633866366335610a313239623765623636656263353463
35616137663932333435663038313936346132613032363664373238613366623864303965663633
6466613435616536330a663039393866666163383662623235346238636336383865363639303337
30346632636164326530323731313436366531616662386365356131323732386138393532663462
66346661316632636135313935333231653165303437333362666639643939393138306635656164
36373333356237656566663231353838333531366337626561313636653961323330393530633336
35393764383831656535616461343832383636616263333138653363666636666530643366653334
36353262353437333733313033633238626664626561356230633462313765353731636435323936
3338366533336661646162306637343431623835396132323638
